kind: pipeline
name: ci

services:
- name: postgres
  image: postgres:9.6.9
  environment:
    POSTGRES_USER: chefbook
    POSTGRES_PASSWORD: admin
    POSTGRES_DB: chefbook_test

steps:
- name: Install Dependencies
  image: node:12
  commands:
  - cd /drone/src/Backend && npm install
  - cd /drone/src/Frontend && npm install
  - cd /drone/src/SharedUtils && npm install
- name: Test Backend
  image: node:12
  environment:
    NODE_ENV: test
    VERBOSE: true
    POSTGRES_DB: chefbook_test
    POSTGRES_USER: chefbook
    POSTGRES_PASSWORD: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: postgres
    POSTGRES_SSL: false
    POSTGRES_LOGGING: false
    GRIP_URL: http://localhost:5561/
    GRIP_KEY: changeme
  commands:
  - cd Backend && npm run test:ci
