kind: pipeline
name: ci-backend

services:
- name: postgres
  image: postgres:9.6.9
  environment:
    POSTGRES_USER: chefbook
    POSTGRES_PASSWORD: admin
    POSTGRES_DB: chefbook_test

steps:
- name: Install Dependencies
  image: node:12
  commands:
  - cd /drone/src/Backend && npm install
  - cd /drone/src/SharedUtils && npm install
- name: Test
  image: node:12
  environment:
    NODE_ENV: development
    VERBOSE: true
    POSTGRES_DB: chefbook_test
    POSTGRES_USER: chefbook
    POSTGRES_PASSWORD: admin
    POSTGRES_PORT: 5432
    POSTGRES_HOST: postgres
    POSTGRES_SSL: false
    POSTGRES_LOGGING: true
    GRIP_URL: http://localhost:5561/
    GRIP_KEY: changeme
  commands:
  - cd Backend && npm run test:ci
- name: Push
  image: node:12
  commands:
  - echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
  - ./scripts/deploy/push_api_docker.sh $DRONE_TAG
  when:
    ref: [ refs/heads/master, refs/tags/* ]

---

kind: pipeline
name: ci-frontend

steps:
- name: Install Dependencies
  image: node:12
  commands:
  - cd /drone/src/Frontend && npm install
  - cd /drone/src/SharedUtils && npm install
- name: Lint
  image: node:12
  commands:
  - cd Frontend && npm run lint
- name: Build
  image: node:12
  commands:
  - cd Frontend && npm run dist
- name: Push
  image: node:12
  commands:
  - echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
  - mv Frontend/www www
  - sed -i "s/window.version = 'development';/window.version = '${DRONE_TAG}';/" www/index.html
  - ./scripts/deploy/push_static_docker.sh $DRONE_TAG
  - ./scripts/deploy/push_static_s3.sh $DRONE_TAG
  when:
    ref: [ refs/heads/master, refs/tags/* ]

